# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Monkey knows SE!
email: lumiere000@protonmail.com
description: >- # this means to ignore newlines until "baseurl:"
  Monkey knows SE! Saru Demo Dekiru System Engineering!
  This blog represent an easiest way to setup/config your system,
  get rid of complicating structure and useless options.
baseurl: / # the subpath of your site, e.g. /blog
url: "http://semonkey.com" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  lumiere000
#permalink: date

# Build settings
markdown: kramdown
#theme: jekyll-theme-slate
#theme: minima
plugins:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed



jquery: 3.1.1
modernizr: 2.8.3




# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
#permalink: /blog/:date
permalink: :year-:month-:day-:title.html




# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
#minima:
#  date_format: "%b %-d, %Y"

#sass:
#  sass_dir:          _scss
#style: :compressed
#variables:
